<?php
$dictionary['voipcalls'] = [
    'table' => 'voipcalls',
    'fields' => [
        'id' => [
            'name' => 'id',
            'type' => 'id',
            'comment' => 'unique identifier: call id generated by voip interface'
        ],
        'channel' => [
            'name' => 'channel',
            'type' => 'varchar',
            'len' => 100,
            'comment' => 'node channel name'
        ],
        'callednumber' => [
            'name' => 'callednumber',
            'type' => 'varchar',
            'len' => 50,
            'comment' => 'called number'
        ],
        'callernumber' => [
            'name' => 'callernumber',
            'type' => 'varchar',
            'len' => 50,
            'comment' => 'caller number'
        ],
        'callstate' => [
            'name' => 'callstate',
            'type' => 'varchar',
            'len' => 50,
            'comment' => 'unified state like dialing, ringing, connected, hangup... '
        ],
        'calldirection' => [
            'name' => 'calldirection',
            'type' => 'varchar',
            'len' => 10,
            'comment' => 'inbound | outbound'
        ],
        'activecallid' => [
            'name' => 'activecallid',
            'type' => 'id',
            'comment' => 'introduced for alcatel'
        ],
    ],
    'indices' => [
        [
            'name' => 'voipcallspk',
            'type' => 'primary',
            'fields' => ['id']
        ],
        [
            'name' => 'idx_voipcalls_activecallid',
            'type' => 'index',
            'fields' => ['activecallid']
        ]
    ]
];
