<?php


use SpiceCRM\includes\SugarObjects\VardefManager;

$dictionary['ServiceFeedback'] = [
    'table'           => 'servicefeedbacks',
    'comment'         => 'ServiceFeedbacks Module',
    'audited'         =>  false,
    'duplicate_merge' =>  false,
    'unified_search'  =>  false,

    'fields' => [
        'parent_id' => [
            'name'       => 'parent_id',
            'vname'      => 'LBL_LIST_RELATED_TO_ID',
            'type'       => 'id',
            'group'      => 'parent_name',
            'reportable' => true,
            'comment'    => 'The ID of the parent Sugar object identified by parent_type',
        ],
        'parent_type' => [
            'name'     => 'parent_type',
            'vname'    => 'LBL_PARENT_TYPE',
            'type'     => 'parent_type',
            'dbType'   => 'varchar',
            'required' => true,
            'group'    => 'parent_name',
            'options'  => 'servicefeedbacks_parent_type_display',
            'len'      => 255,
            'comment'  => 'The Sugar object to which the call is related',
        ],
        'parent_name' => [
            'name'        => 'parent_name',
            'parent_type' => 'servicefeedbacks_record_type_display',
            'type_name'   => 'parent_type',
            'id_name'     => 'parent_id',
            'vname'       => 'LBL_RELATED_TO',
            'type'        => 'parent',
            'group'       => 'parent_name',
            'source'      => 'non-db',
            'options'     => 'servicefeedbacks_parent_type_display',
        ],
        'comment' => [
            'name'       => 'comment',
            'vname'      => 'LBL_COMMENT',
            'type'       => 'text',
            'reportable' => true,
            'comment'    => 'comment writen by recipient',

        ],
        'suggestion' => [
            'name'       => 'suggestion',
            'vname'      => 'LBL_SUGGESTION',
            'type'       => 'text',
            'reportable' => true,
            'comment'    => 'comment writen by recipient',
        ],
        'responsetime' => [
            'name'       => 'responsetime',
            'vname'      => 'LBL_RESPONSE_TIME',
            'type'       => 'enum',
            'options'    => 'service_satisfaction_scale_dom',
            'dbType'     => 'int',
            'reportable' => true,
            'comment'    => 'Customer satisfaction',
        ],
        'responsequality' => [
            'name'       => 'responsequality',
            'vname'      => 'LBL_QUALITY',
            'type'       => 'enum',
            'options'    => 'service_satisfaction_scale_dom',
            'dbType'     => 'int',
            'reportable' => true,
            'comment'    => 'Customer satisfaction - staff work',
        ],
        'responsefriendlyness' => [
            'name'       => 'responsefriendlyness',
            'vname'      => 'LBL_FRIENDLYNESS',
            'type'       => 'enum',
            'options'    => 'service_satisfaction_scale_dom',
            'dbType'     => 'int',
            'reportable' => true,
            'comment'    => 'Customer satisfaction - staff friendlyness',
        ],
        'servicefeedback_status' => [
            'name'       => 'servicefeedback_status',
            'vname'      => 'LBL_SERVICEFEEDBACK_STATUS',
            'type'       => 'enum',
            'options'    => 'servicefeedback_status_dom',
            'reportable' => true,
            'comment'    => 'Status',
        ],
        //contact
        'contact_id' => [
            'name'       => 'contact_id',
            'vname'      => 'LBL_CONTACT_ID',
            'type'       => 'id',
            'reportable' => true,
            'comment'    => 'The ID of the recipient',
        ],
        'contact_name' => [
            'name'             => 'contact_name',
            'vname'            => 'LBL_CONTACT',
            'type'             => 'relate',
            'source'           => 'non-db',
            'len'              => '255',
            'id_name'          => 'contact_id',
            'rname'            => 'last_name',
            'module'           => 'Contacts',
            'link'             => 'contacts',
            'join_name'        => 'contacts',
            'db_concat_fields' => [
                0 => 'first_name',
                1 => 'last_name'
            ],
        ],
        'contacts' => [
            'vname'        => 'LBL_CONTACTS',
            'name'         => 'contacts',
            'type'         => 'link',
            'module'       => 'Contacts',
            'relationship' => 'servicefeedbacks_contacts',
            'link_type'    => 'one',
            'side'         => 'right',
            'source'       => 'non-db',
        ],
        //servicetickets
        'servicetickets' => [
            'vname'        => 'LBL_SERVICETICKET',
            'name'         => 'servicetickets',
            'type'         => 'link',
            'module'       => 'ServiceTickets',
            'relationship' => 'servicefeedbacks_servicetickets',
            'link_type'    => 'one',
            'side'         => 'right',
            'source'       => 'non-db',
        ],
        //serviceorders
        'serviceorders' => [
            'vname'        => 'LBL_SERVICEORDER',
            'name'         => 'serviceorders',
            'type'         => 'link',
            'module'       => 'ServiceOrders',
            'relationship' => 'servicefeedbacks_serviceorders',
            'link_type'    => 'one',
            'side'         => 'right',
            'source'       => 'non-db',
        ],
        //servicecalls
        'servicecalls' => [
            'vname'        => 'LBL_SERVICECALL',
            'name'         => 'servicecalls',
            'type'         => 'link',
            'module'       => 'ServiceCalls',
            'relationship' => 'servicefeedbacks_servicecalls',
            'link_type'    => 'one',
            'side'         => 'right',
            'source'       => 'non-db',
        ],
        //campaigntasks
        'campaigntasks' => [
            'vname'        => 'LBL_CAMPAIGNTASK',
            'name'         => 'campaigntasks',
            'type'         => 'link',
            'module'       => 'CampaignTasks',
            'relationship' => 'servicefeedbacks_campaigntasks',
            'link_type'    => 'one',
            'source'       => 'non-db'
        ],
        //questionnaire
        'questionnaire_id' => [
            'name'       => 'questionnaire_id',
            'vname'      => 'LBL_QUESTIONNAIRE_ID',
            'type'       => 'id',
            'reportable' => true,
            'comment'    => 'The ID of the questionnaire',
            'required'   => false,
        ],
        'questionnaire_name' => [
            'name'             => 'questionnaire_name',
            'vname'            => 'LBL_QUESTIONNAIRE',
            'type'             => 'relate',
            'source'           => 'non-db',
            'len'              => '255',
            'id_name'          => 'questionnaire_id',
            'rname'            => 'name',
            'module'           => 'Questionnaires',
            'link'             => 'questionnaires',
            'join_name'        => 'questionnaires',
        ],
        'questionnaires' => [
            'vname'        => 'LBL_QUESTIONNAIRES',
            'name'         => 'questionnaires',
            'type'         => 'link',
            'module'       => 'Questionnaires',
            'relationship' => 'servicefeedbacks_questionnaires',
            'link_type'    => 'one',
            'side'         => 'right',
            'source'       => 'non-db',
        ],
        // questionnaireevaluations
        'questionnaireevaluation_id' => [
            'name'       => 'questionnaireevaluation_id',
            'vname'      => 'LBL_QUESTIONNAIRE_EVALUATION_ID',
            'type'       => 'id',
            'reportable' => true,
            'comment'    => 'The ID of the questionnaire evaluation',
            'required'   => false,
        ],
        'questionnaireevaluation_name' => [
            'name'             => 'questionnaireevaluation_name',
            'vname'            => 'LBL_QUESTIONNAIRE_EVALUATION',
            'type'             => 'relate',
            'source'           => 'non-db',
            'len'              => '255',
            'id_name'          => 'questionnaireevaluation_id',
            'rname'            => 'name',
            'module'           => 'QuestionnaireEvaluations',
            'link'             => 'questionnaireevaluation',
            'join_name'        => 'questionnaireevaluations',
        ],
        'questionnaireevaluation' => [
            'name'         => 'questionnaireevaluation',
            'vname'        => 'LBL_QUESTIONNAIRE_EVALUATION',
            'type'         => 'link',
            'module'       => 'QuestionnaireEvaluations',
            'relationship' => 'servicefeedbacks_questionnaireevaluations',
            'link_type'    => 'one',
            'side'         => 'left',
            'source'       => 'non-db',
            'reportable' => true,
            'comment'    => 'The evaluation of the questionnaire participation.',
            'default' => true,
        ],
        'questionsetparticipations' => [
            'name'         => 'questionsetparticipations',
            'vname'        => 'LBL_QUESTIONSETPARTICIPATIONS',
            'type'         => 'link',
            'module'       => 'QuestionSetParticipations',
            'relationship' => 'servicefeedbacks_questionsetparticipations',
            'link_type'    => 'one',
            'source'       => 'non-db'
        ]
    ],
    'relationships' => [
        'servicefeedbacks_contacts' => [
            'lhs_module'        => 'Contacts',
            'lhs_table'         => 'contacts',
            'lhs_key'           => 'id',
            'rhs_module'        => 'ServiceFeedbacks',
            'rhs_table'         => 'servicefeedbacks',
            'rhs_key'           => 'contact_id',
            'relationship_type' => 'one-to-many',
        ],
        'servicefeedbacks_servicetickets' => [
            'lhs_module'                     => 'ServiceTickets',
            'lhs_table'                      => 'servicetickets',
            'lhs_key'                        => 'id',
            'rhs_module'                     => 'ServiceFeedbacks',
            'rhs_table'                      => 'servicefeedbacks',
            'rhs_key'                        => 'parent_id',
            'relationship_type'              => 'one-to-many',
            'relationship_role_column'       => 'parent_type',
            'relationship_role_column_value' => 'ServiceTickets',
        ],
        'servicefeedbacks_serviceorders' => [
            'lhs_module'                     => 'ServiceOrders',
            'lhs_table'                      => 'serviceorders',
            'lhs_key'                        => 'id',
            'rhs_module'                     => 'ServiceFeedbacks',
            'rhs_table'                      => 'servicefeedbacks',
            'rhs_key'                        => 'parent_id',
            'relationship_type'              => 'one-to-many',
            'relationship_role_column'       => 'parent_type',
            'relationship_role_column_value' => 'ServiceOrders',
        ],
        'servicefeedbacks_servicecalls' => [
            'lhs_module'                     => 'ServiceCalls',
            'lhs_table'                      => 'servicecalls',
            'lhs_key'                        => 'id',
            'rhs_module'                     => 'ServiceFeedbacks',
            'rhs_table'                      => 'servicefeedbacks',
            'rhs_key'                        => 'parent_id',
            'relationship_type'              => 'one-to-many',
            'relationship_role_column'       => 'parent_type',
            'relationship_role_column_value' => 'ServiceCalls',
        ],
        'servicefeedbacks_campaigntasks' => [
            'lhs_module'                     => 'CampaignTasks',
            'lhs_table'                      => 'campaigntasks',
            'lhs_key'                        => 'id',
            'rhs_module'                     => 'ServiceFeedbacks',
            'rhs_table'                      => 'servicefeedbacks',
            'rhs_key'                        => 'parent_id',
            'relationship_type'              => 'one-to-many',
            'relationship_role_column'       => 'parent_type',
            'relationship_role_column_value' => 'CampaignTasks',
        ],
        'servicefeedbacks_questionnaires' => [
            'lhs_module'        => 'Questionnaires',
            'lhs_table'         => 'questionnaires',
            'lhs_key'           => 'id',
            'rhs_module'        => 'ServiceFeedbacks',
            'rhs_table'         => 'servicefeedbacks',
            'rhs_key'           => 'questionnaire_id',
            'relationship_type' => 'one-to-many',
        ],
        'servicefeedbacks_questionnaireevaluations' => [
            'rhs_module'        => 'QuestionnaireEvaluations',
            'rhs_table'         => 'questionnaireevaluations',
            'rhs_key'           => 'id',
            'lhs_module'        => 'ServiceFeedbacks',
            'lhs_table'         => 'servicefeedbacks',
            'lhs_key'           => 'questionnaireevaluation_id',
            'relationship_type' => 'one-to-many',
        ],
        'servicefeedbacks_questionsetparticipations' => [
            'rhs_module'        => 'QuestionSetParticipations',
            'rhs_table'         => 'questionsetparticipations',
            'rhs_key'           => 'referenceid',
            'lhs_module'        => 'ServiceFeedbacks',
            'lhs_table'         => 'servicefeedbacks',
            'lhs_key'           => 'id',
            'relationship_type' => 'one-to-many',
        ],
    ],
    'indices' => [
        ['name' => 'idx_servicefeedback_parent', 'type' => 'index', 'fields' => ['parent_id', 'parent_type']],
        ['name' => 'idx_servicefeedback_parenttype', 'type' => 'index', 'fields' => ['parent_type', 'deleted']],
        ['name' => 'idx_servicefeedback_cnt', 'type' => 'index', 'fields' => ['contact_id']],
        ['name' => 'idx_servicefeedback_qst', 'type' => 'index', 'fields' => ['questionnaire_id']],
        ['name' => 'idx_servicefeedback_qsteval', 'type' => 'index', 'fields' => ['questionnaireevaluation_id']],
    ],
];

VardefManager::createVardef('ServiceFeedbacks', 'ServiceFeedback', ['default', 'assignable']);


//name is not required. Overwrite default
//set global else error with PHP7.1: Uncaught Error: Cannot use string offset as an array
global $dictionary;
$dictionary['ServiceFeedback']['fields']['name']['required'] = false;
