<?php

use SpiceCRM\includes\SugarObjects\VardefManager;

$dictionary['SalesDoc'] = array(
    'table' => 'salesdocs',
    'audited' => true,
    'fields' => array(
        'salesdocnumber' => array(
            'name' => 'salesdocnumber',
            'vname' => 'LBL_DOCNUMBER',
            'type' => 'varchar',
            'len' => 40,
            'required' => false,
            'reportable' => true,
            'massupdate' => false,
        ),
        'salesdocdate' => array(
            'name' => 'salesdocdate',
            'vname' => 'LBL_DATE_DOCUMENT',
            'type' => 'date',
            'required' => true
        ),
        'salesdoctype' => array(
            'name' => 'salesdoctype',
            'vname' => 'LBL_DOCUMENTTYPE',
            'type' => 'salesdoctype',
            'dbType' => 'varchar',
            'len' => 12,
            'required' => true
        ),
        'salesdoccategory' => array(
            'name' => 'salesdoccategory',
            'vname' => 'LBL_DOCUMENTCATEGORY',
            'type' => 'enum',
            'len' => 2,
            'options' => 'salesdoc_doccategories',
            'required' => false
        ),
        'salesdocparty' => array(
            'name' => 'salesdocparty',
            'vname' => 'LBL_SALESDOCPARTY',
            'type' => 'enum',
            'len' => 1,
            'options' => 'salesdoc_docparties',
            'required' => true
        ),
        'delivery_date' => array(
            'name' => 'delivery_date',
            'vname' => 'LBL_DELIVERY_DATE',
            'type' => 'date',
            'required' => false
        ),
        'valid_from_date' => array(
            'name' => 'valid_from_date',
            'vname' => 'LBL_VALID_FROM',
            'type' => 'date',
            'required' => false
        ),
        'valid_until_date' => array(
            'name' => 'valid_until_date',
            'vname' => 'LBL_VALID_UNTIL',
            'type' => 'date',
            'required' => false
        ),
        'currency_id' => array(
            'name' => 'currency_id',
            'type' => 'id',
            'group' => 'currency_id',
            'vname' => 'LBL_CURRENCY',
            'reportable' => false,
            'comment' => 'Currency used for display purposes'
        ),
        'currency_name' => array(
            'name' => 'currency_name',
            'rname' => 'name',
            'id_name' => 'currency_id',
            'vname' => 'LBL_CURRENCY',
            'type' => 'relate',
            'isnull' => 'true',
            'table' => 'currencies',
            'module' => 'Currencies',
            'source' => 'non-db',
            'function' => array('name' => 'getCurrencyNameDropDown', 'returns' => 'html'),
            'studio' => 'false',
            'duplicate_merge' => 'disabled',
        ),
        'currency_display' => array(
            'name' => 'currency_display',
            'vname' => 'LBL_CURRENCY_ISO4217',
            'type' => 'varchar',
            'source' => 'non-db'
        ),
        'paymentterms' => array(
            'name' => 'paymentterms',
            'vname' => 'LBL_PAYMENTTERMS',
            'type' => 'enum',
            'len' => 10,
            'options' => 'salesdocs_paymentterms',
            'required' => true
        ),
        'ponumber' => array(
            'name' => 'ponumber',
            'vname' => 'LBL_PONUMBER',
            'type' => 'varchar',
            'len' => 45
        ),
        'podate' => array(
            'name' => 'podate',
            'vname' => 'LBL_PODATE',
            'type' => 'date'
        ),
        'poreference' => array(
            'name' => 'poreference',
            'vname' => 'LBL_POREFERENCE',
            'type' => 'varchar',
            'len' => 45
        ),
        // amount values
        'amount_net' => array(
            'name' => 'amount_net',
            'vname' => 'LBL_AMOUNT_NET',
            'type' => 'currency',
            'dbType' => 'double',
            'currency_id' => 'currency_id',
            'source' => 'non-db'

        ),
        'amount_gross' => array(
            'name' => 'amount_gross',
            'vname' => 'LBL_AMOUNT_GROSS',
            'type' => 'currency',
            'dbType' => 'double',
            'currency_id' => 'currency_id',
            'source' => 'non-db'

        ),
        'tax_amount' => array(
            'name' => 'tax_amount',
            'vname' => 'LBL_TAX_AMOUNT',
            'type' => 'currency',
            'dbType' => 'double',
            'currency_id' => 'currency_id',
            'source' => 'non-db'
        ),
        'record_source' => array(
            'name' => 'record_source',
            'vname' => 'LBL_SOURCE',
            'type' => 'varchar',
            'len' => 16,
            'comment' => 'protocol how record entered crm. Might be created by external ERP System or so',
        ),
        // aproval
        'date_approved' => array(
            'name' => 'date_approved',
            'vname' => 'LBL_DATE_APPROVED',
            'type' => 'datetime',
            'audited' => true
        ),
        'approved_user_id' => array(
            'name' => 'approved_user_id',
            'vname' => 'LBL_APPROVED_USER_ID',
            'type' => 'id',
            'table' => 'users',
            'isnull' => 'false',
            'dbType' => 'id',
        ),
        'approved_user_link' => array(
            'name' => 'approved_user_link',
            'type' => 'link',
            'relationship' => 'salesdocs_approved_user',
            'vname' => 'LBL_APPROVED_USER_LINK',
            'link_type' => 'one',
            'module' => 'Users',
            'bean_name' => 'User',
            'source' => 'non-db',
        ),
        'approved_by_name' => array(
            'name' => 'approved_by_name',
            'vname' => 'LBL_APPROVED_USER_NAME',
            'type' => 'relate',
            'source' => 'non-db',
            'rname' => 'user_name',
            'table' => 'users',
            'id_name' => 'approved_user_id',
            'module' => 'Users',
            'link' => 'approved_user_link',
            'duplicate_merge' => 'disabled',
            'massupdate' => false,
        ),
        // linked fields
        'companycode_id' => array(
            'name' => 'companycode_id',
            'vname' => 'LBL_COMPANYCODE',
            'type' => 'id',
            'audited' => true,
            'required' => true
        ),
        'companycode_name' => array(
            'name' => 'companycode_name',
            'rname' => 'name',
            'id_name' => 'companycode_id',
            'vname' => 'LBL_COMPANY',
            'type' => 'relate',
            'link' => 'salesdocs_companycodes',
            'isnull' => 'true',
            'table' => 'companycodes',
            'module' => 'CompanyCodes',
            'source' => 'non-db'
        ),
        'salesdocs_companycodes' => array(
            'name' => 'salesdocs_companycodes',
            'type' => 'link',
            'vname' => 'LBL_SALESDOCS_COMPANYCODES',
            'relationship' => 'salesdocs_companycodes',
            'source' => 'non-db',
        ),
        // linked fields 
        'contact_id' => array(
            'name' => 'contact_id',
            'vname' => 'LBL_CONTACT_ID',
            'type' => 'id',
            'audited' => true,
        ),
        'contact_name' => array(
            'name' => 'contact_name',
            'rname' => 'name',
            'db_concat_fields' => [
                0 => 'salutation',
                0 => 'degree1',
                2 => 'first_name',
                3 => 'last_name',
                3 => 'degree2'
            ],
            'id_name' => 'contact_id',
            'vname' => 'LBL_CONTACT',
            'type' => 'relate',
            'link' => 'salesdocs_contacts',
            'isnull' => 'true',
            'table' => 'contacts',
            'module' => 'Contacts',
            'source' => 'non-db',
        ),
        'salesdocs_contacts' => array(
            'name' => 'salesdocs_contacts',
            'type' => 'link',
            'vname' => 'LBL_SALESDOCS_CONTACTS',
            'relationship' => 'salesdocs_contacts',
            'source' => 'non-db',
        ),
        'account_op_id' => array(
            'name' => 'account_op_id',
            'vname' => 'LBL_ACCOUNT_OP_ID',
            'type' => 'varchar',
            'len' => 36,
            'audited' => true,
            'comment' => 'ordering party'
        ),
        'account_op_name' => array(
            'name' => 'account_op_name',
            'rname' => 'name',
            'id_name' => 'account_op_id',
            'vname' => 'LBL_ACCOUNTOP',
            'type' => 'relate',
            'link' => 'salesdocs_accountsop',
            'isnull' => 'true',
            'table' => 'accounts',
            'module' => 'Accounts',
            'source' => 'non-db',
        ),
        'salesdocs_accountsop' => array(
            'name' => 'salesdocs_accountsop',
            'type' => 'link',
            'vname' => 'LBL_SALESDOCS_ACCOUNTSOP',
            'relationship' => 'salesdocs_accountsop',
            'source' => 'non-db',
        ),
        'account_rp_id' => array(
            'name' => 'account_rp_id',
            'vname' => 'LBL_ACCOUNT_RP_ID',
            'type' => 'varchar',
            'len' => 36,
            'comment' => 'receiving party'
        ),
        'account_rp_name' => array(
            'name' => 'account_rp_name',
            'rname' => 'name',
            'id_name' => 'account_rp_id',
            'vname' => 'LBL_ACCOUNTRP',
            'type' => 'relate',
            'link' => 'salesdocs_accountsrp',
            'isnull' => 'true',
            'table' => 'accounts',
            'module' => 'Accounts',
            'source' => 'non-db',
        ),
        'account_pp_id' => array(
            'name' => 'account_pp_id',
            'vname' => 'LBL_ACCOUNT_PP_ID',
            'type' => 'varchar',
            'len' => 36,
            'audited' => true,
            'comment' => 'payment processor'
        ),
        'account_pp_name' => array(
            'name' => 'account_pp_name',
            'rname' => 'name',
            'id_name' => 'account_pp_id',
            'vname' => 'LBL_ACCOUNTPP',
            'type' => 'relate',
            'link' => 'salesdocs_accountspp',
            'isnull' => 'true',
            'table' => 'accounts',
            'module' => 'Accounts',
            'source' => 'non-db',
        ),
        'account_ir_id' => array(
            'name' => 'account_ir_id',
            'vname' => 'LBL_ACCOUNT_IR_ID',
            'type' => 'varchar',
            'len' => 36,
            'audited' => true,
            'comment' => 'invoice receipient'
        ),
        'account_ir_name' => array(
            'name' => 'account_ir_name',
            'rname' => 'name',
            'id_name' => 'account_ir_id',
            'vname' => 'LBL_ACCOUNTIR',
            'type' => 'relate',
            'link' => 'salesdocs_accountsir',
            'isnull' => 'true',
            'table' => 'accounts',
            'module' => 'Accounts',
            'source' => 'non-db',
        ),
        'salesdocs_accountspp' => array(
            'name' => 'salesdocs_accountspp',
            'type' => 'link',
            'vname' => 'LBL_SALESDOCS_ACCOUNTSPP',
            'relationship' => 'salesdocs_accountspp',
            'source' => 'non-db',
        ),
        'salesdocs_accountsir' => array(
            'name' => 'salesdocs_accountsir',
            'type' => 'link',
            'vname' => 'LBL_SALESDOCS_ACCOUNTSIR',
            'relationship' => 'salesdocs_accountsir',
            'source' => 'non-db',
        ),


        'salesdocs_accountsrp' => array(
            'name' => 'salesdocs_accountsrp',
            'type' => 'link',
            'vname' => 'LBL_SALESDOCS_ACCOUNTSRP',
            'relationship' => 'salesdocs_accountsrp',
            'source' => 'non-db',
        ),
        'contact_op_id' => array(
            'name' => 'contact_op_id',
            'vname' => 'LBL_CONTACT_OP_ID',
            'type' => 'varchar',
            'len' => 36,
            'audited' => true,
        ),
        'contact_op_name' => array(
            'name' => 'contact_op_name',
            'rname' => 'name',
            'id_name' => 'contact_op_id',
            'vname' => 'LBL_CONTACTOP',
            'type' => 'relate',
            'link' => 'salesdocs_contactsop',
            'isnull' => 'true',
            'table' => 'contacts',
            'module' => 'Contacts',
            'source' => 'non-db',
        ),
        'salesdocs_contactsop' => array(
            'name' => 'salesdocs_contactsop',
            'type' => 'link',
            'vname' => 'LBL_SALESDOCS_CONTACTSOP',
            'relationship' => 'salesdocs_contactsop',
            'source' => 'non-db',
        ),
        'contact_rp_id' => array(
            'name' => 'contact_rp_id',
            'vname' => 'LBL_CONTACT_RP_ID',
            'type' => 'varchar',
            'len' => 36,
            'audited' => true,
        ),
        'contact_rp_name' => array(
            'name' => 'contact_rp_name',
            'rname' => 'name',
            'id_name' => 'contact_rp_id',
            'vname' => 'LBL_CONTACTRP',
            'type' => 'relate',
            'link' => 'salesdocs_contactsrp',
            'isnull' => 'true',
            'table' => 'contacts',
            'module' => 'Contacts',
            'source' => 'non-db',
        ),
        'salesdocs_contactsrp' => array(
            'name' => 'salesdocs_contactsrp',
            'type' => 'link',
            'vname' => 'LBL_SALESDOCS_CONTACTSRP',
            'relationship' => 'salesdocs_contactsrp',
            'source' => 'non-db',
        ),

        'salesdocsquotes2orders' => array(
            'name' => 'salesdocsquotes2orders',
            'type' => 'link',
            'vname' => 'LBL_SALESDOCSQUOTES2ORDERS',
            'relationship' => 'salesdocsquotes_salesdocsorders',
            'source' => 'non-db',
        ),
        'salesdocsorders2quotes' => array(
            'name' => 'salesdocsorders2quotes',
            'type' => 'link',
            'vname' => 'LBL_SALESDOCSORDERS2QUOTES',
            'relationship' => 'salesdocsquotes_salesdocsorders',
            'source' => 'non-db',
        ),

        'salesdocsquotes2contracts' => array(
            'name' => 'salesdocsquotes2contracts',
            'type' => 'link',
            'vname' => 'LBL_SALESDOCSQUOTES2CONTRACTS',
            'relationship' => 'salesdocsquotes_salesdocscontracts',
            'source' => 'non-db',
        ),
        'salesdocscontracts2quotes' => array(
            'name' => 'salesdocscontracts2quotes',
            'type' => 'link',
            'vname' => 'LBL_SALESDOCSCONTRACTS2QUOTES',
            'relationship' => 'salesdocsquotes_salesdocscontracts',
            'source' => 'non-db',
        ),
        'salesdocsorders2invoices' => array(
            'name' => 'salesdocsorders2invoices',
            'type' => 'link',
            'vname' => 'LBL_SALESDOCSORDERS2INVOICES',
            'relationship' => 'salesdocsorders_salesdocsinvoices',
            'source' => 'non-db',
        ),
        'salesdocsinvoices2orders' => array(
            'name' => 'salesdocsinvoices2orders',
            'type' => 'link',
            'vname' => 'LBL_SALESDOCSINVOICES2ORDERS',
            'relationship' => 'salesdocsorders_salesdocsinvoices',
            'source' => 'non-db',
        ),

        'salesdocscontracts2invoices' => array(
            'name' => 'salesdocscontracts2invoices',
            'type' => 'link',
            'vname' => 'LBL_SALESDOCSCONTRACTS2INVOICES',
            'relationship' => 'salesdocscontracts_salesdocsinvoices',
            'source' => 'non-db',
        ),
        'salesdocsinvoices2contracts' => array(
            'name' => 'salesdocsinvoices2contracts',
            'type' => 'link',
            'vname' => 'LBL_SALESDOCSINVOICES2CONTRACTS',
            'relationship' => 'salesdocscontracts_salesdocsinvoices',
            'source' => 'non-db',
        ),
        'salesdocitems' => array(
            'name' => 'salesdocitems',
            'type' => 'link',
            'vname' => 'LBL_SALESDOCS_SALESDOCITEMS',
            'relationship' => 'salesdocs_salesdocitems',
            'source' => 'non-db',
            'module' => 'SalesDocItems',
            'default' => true,
            'sort' => array(
                'sortfield' => 'itemnr',
                'sortdirection' => 'ASC'
            )
        ),
        'salesvouchers' => array(
            'name' => 'salesvouchers',
            'type' => 'link',
            'relationship' => 'salesdocs_salesvouchers',
            'source' => 'non-db',
            'side' => 'right',
            'module' => 'SalesVouchers',
            'vname' => 'LBL_SALESDOCS_SALESVOUCHERS_LINK',
            'default' => true
        ),
        'outputtemplate_id' => [
            'name' => 'outputtemplate_id',
            'type' => 'varchar',
            'len' => 36,
            'required' => false,
            'vname' => 'LBL_OUTPUT_TEMPLATE',
        ],
        'outputtemplate' => [
            'name' => 'outputtemplate',
            'type' => 'link',
            'module' => 'OutputTemplates',
            'relationship' => 'outputtemplate_salesdocs',
            'source' => 'non-db',
        ],
        'outputtemplate_name' => [
            'name' => 'outputtemplate_name',
            'rname' => 'name',
            'id_name' => 'outputtemplate_id',
            'type' => 'relate',
            'link' => 'outputtemplate',
            'table' => 'outputtemplates',
            'module' => 'OutputTemplates',
            'source' => 'non-db',
            'vname' => 'LBL_OUTPUT_TEMPLATE',
        ],
        'lead_id' => [
            'name' => 'lead_id',
            'type' => 'varchar',
            'len' => 36,
            'required' => false,
            'vname' => 'LBL_LEAD_ID',
        ],
        'lead' => [
            'name' => 'lead',
            'vname' => 'LBL_LEADS',
            'type' => 'link',
            'module' => 'Leads',
            'relationship' => 'lead_salesdocs',
            'source' => 'non-db',
        ],
        'lead_name' => [
            'name' => 'lead_name',
            'rname' => 'name',
            'id_name' => 'lead_id',
            'type' => 'relate',
            'link' => 'lead',
            'table' => 'leads',
            'module' => 'Leads',
            'source' => 'non-db',
            'vname' => 'LBL_LEAD',
        ],
        'incoterm1' => [
            'name' => 'incoterm1',
            'vname' => 'LBL_INCOTERM1',
            'type' => 'enum',
            'dbType' => 'char',
            'len' => 3,
            'options' => 'incoterms_dom',
            'comment' => 'incoterm key'
        ],
        'incoterm2' => [
            'name' => 'incoterm2',
            'vname' => 'LBL_INCOTERM2',
            'type' => 'varchar',
            'comment' => 'incoterm location'
        ],
        'parent_id' => [
            'name' => 'parent_id',
            'vname' => 'LBL_PARENT_ID',
            'type' => 'id',
        ],
        'parent_type' => [
            'name' => 'parent_type',
            'vname' => 'LBL_PARENT_TYPE',
            'type' => 'varchar',
            'options' => 'salesdocs_parent_type_display'
        ],
        'parent_name' => [
            'name' => 'parent_name',
            'type_name' => 'parent_type',
            'id_name' => 'parent_id',
            'vname' => 'LBL_RELATED_TO',
            'type' => 'parent',
            'source' => 'non-db',
            'options' => 'salesdocs_parent_type_display'
        ],
        'serviceequipments' => [
            'name' => 'serviceequipments',
            'vname' => 'LBL_SERVICEEQUIPMENTS',
            'type' => 'link',
            'source' => 'non-db',
            'module' => 'ServiceEquipments',
            'relationship' => 'salesdocs_serviceequipments',
            'default' => true
        ],
        'salesdoc_status' => [
            'name' => 'salesdoc_status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'options' => 'salesdoc_status_dom'
        ],
        'consumer_op_id' => [
            'name' => 'consumer_op_id',
            'vname' => 'LBL_CONSUMER_RP_ID',
            'type' => 'varchar',
            'len' => 36,
            'audited' => true,
            'comment' => 'ordering consumer'
        ],
        'consumer_op_name' => [
            'name' => 'consumer_op_name',
            'rname' => 'name',
            'id_name' => 'consumer_op_id',
            'vname' => 'LBL_CONSUMER_OP',
            'type' => 'relate',
            'link' => 'consumer_op',
            'isnull' => 'true',
            'table' => 'consumers',
            'module' => 'Consumers',
            'source' => 'non-db',
        ],
        'consumer_rp_id' => [
            'name' => 'consumer_rp_id',
            'vname' => 'LBL_CONSUMER_RP_ID',
            'type' => 'varchar',
            'len' => 36,
            'audited' => true,
            'comment' => 'receiving consumer'
        ],
        'consumer_rp_name' => [
            'name' => 'consumer_rp_name',
            'rname' => 'name',
            'id_name' => 'consumer_rp_id',
            'vname' => 'LBL_CONSUMER_RP',
            'type' => 'relate',
            'link' => 'consumer_rp',
            'isnull' => 'true',
            'table' => 'consumers',
            'module' => 'Consumers',
            'source' => 'non-db',
        ],
        'billing_address_name' => array(
            'name' => 'billing_address_name',
            'vname' => 'LBL_BILLING_ADDRESS_NAME',
            'type' => 'varchar',
            'len' => '150',
            'comment' => 'The name used for billing address'
        ),
        'billing_address_phone' => array(
            'name' => 'billing_address_phone',
            'vname' => 'LBL_BILLING_ADDRESS_PHONE',
            'type' => 'varchar',
            'len' => '50',
            'comment' => 'The phone used for billing address'
        ),
        'billing_address_street' => array(
            'name' => 'billing_address_street',
            'vname' => 'LBL_BILLING_ADDRESS_STREET',
            'type' => 'varchar',
            'len' => '150',
            'comment' => 'The street address used for billing address',
            'group' => 'billing_address',
            'merge_filter' => 'enabled',
        ),
        'billing_address_street_2' => array(
            'name' => 'billing_address_street_2',
            'vname' => 'LBL_BILLING_ADDRESS_STREET_2',
            'type' => 'varchar',
            'len' => '80',
        ),
        'billing_address_street_3' => array(
            'name' => 'billing_address_street_3',
            'vname' => 'LBL_BILLING_ADDRESS_STREET_3',
            'type' => 'varchar',
            'len' => '80',
        ),
        'billing_address_street_number' => array(
            'name' => 'billing_address_street_number',
            'vname' => 'LBL_BILLING_ADDRESS_STREET_NUMBER',
            'type' => 'varchar',
            'len' => 10,
        ),
        'billing_address_street_number_suffix' => array(
            'name' => 'billing_address_street_suffix',
            'vname' => 'LBL_BILLING_ADDRESS_STREET_NUMBER_SUFFIX',
            'type' => 'varchar',
            'len' => 25,
            'comment' => 'additonal info to the street like Appartmnent, Floor, etc',
        ),
        'billing_address_attn' => array(
            'name' => 'billing_address_attn',
            'vname' => 'LBL_BILLING_ADDRESS_ATTN',
            'type' => 'varchar',
            'len' => '150',
            'comment' => 'additonal attention field for the address',
            'group' => 'billing_address',
            'merge_filter' => 'enabled',
        ),
        'billing_address_city' => array(
            'name' => 'billing_address_city',
            'vname' => 'LBL_BILLING_ADDRESS_CITY',
            'type' => 'varchar',
            'len' => '100',
            'comment' => 'The city used for billing address',
            'group' => 'billing_address',
            'merge_filter' => 'enabled',
        ),
        'billing_address_district' => array(
            'name' => 'billing_address_district',
            'vname' => 'LBL_BILLING_ADDRESS_DISTRICT',
            'type' => 'varchar',
            'len' => 100,
            'group' => 'billing_address',
            'comment' => 'The district used for the billing address',
        ),
        'billing_address_state' => array(
            'name' => 'billing_address_state',
            'vname' => 'LBL_BILLING_ADDRESS_STATE',
            'type' => 'varchar',
            'len' => '100',
            'group' => 'billing_address',
            'comment' => 'The state used for billing address',
            'merge_filter' => 'enabled',
        ),
        'billing_address_postalcode' => array(
            'name' => 'billing_address_postalcode',
            'vname' => 'LBL_BILLING_ADDRESS_POSTALCODE',
            'type' => 'varchar',
            'len' => '20',
            'group' => 'billing_address',
            'comment' => 'The postal code used for billing address',
            'merge_filter' => 'enabled',
        ),
        'billing_address_pobox' => array(
            'name' => 'billing_address_pobox',
            'vname' => 'LBL_BILLING_ADDRESS_POBOX',
            'type' => 'varchar',
            'len' => '20',
            'group' => 'billing_address',
            'comment' => 'The pobox used for billing address',
            'merge_filter' => 'enabled',
        ),
        'billing_address_country' => array(
            'name' => 'billing_address_country',
            'vname' => 'LBL_BILLING_ADDRESS_COUNTRY',
            'type' => 'varchar',
            'group' => 'billing_address',
            'comment' => 'The country used for the billing address',
            'merge_filter' => 'enabled',
        ),
        'billing_address_latitude' => array(
            'name' => 'billing_address_latitude',
            'vname' => 'LBL_BILLING_ADDRESS_LATITUDE',
            'type' => 'double',
            'group' => 'billing_address',
        ),
        'billing_address_longitude' => array(
            'name' => 'billing_address_longitude',
            'vname' => 'LBL_BILLING_ADDRESS_LONGITUDE',
            'type' => 'double',
            'group' => 'billing_address',
        ),
        'shipping_address_name' => array(
            'name' => 'shipping_address_name',
            'vname' => 'LBL_SHIPPING_ADDRESS_NAME',
            'type' => 'varchar',
            'len' => '150',
            'comment' => 'The name used for shipping address'
        ),
        'shipping_address_phone' => array(
            'name' => 'shipping_address_phone',
            'vname' => 'LBL_SHIPPING_ADDRESS_PHONE',
            'type' => 'varchar',
            'len' => '50',
            'comment' => 'The phone used for shipping address'
        ),
        'shipping_address_street' => array(
            'name' => 'shipping_address_street',
            'vname' => 'LBL_SHIPPING_ADDRESS_STREET',
            'type' => 'varchar',
            'len' => 150,
            'group' => 'shipping_address',
            'comment' => 'The street address used for for shipping purposes',
            'merge_filter' => 'enabled',
        ),
        'shipping_address_street_2' => array(
            'name' => 'shipping_address_street_2',
            'vname' => 'LBL_SHIPPING_ADDRESS_STREET_2',
            'type' => 'varchar',
            'len' => 80,
        ),
        'shipping_address_street_3' => array(
            'name' => 'shipping_address_street_3',
            'vname' => 'LBL_SHIPPING_ADDRESS_STREET_3',
            'type' => 'varchar',
            'len' => 80,
        ),
        'shipping_address_street_4' => array(
            'name' => 'shipping_address_street_4',
            'vname' => 'LBL_SHIPPING_ADDRESS_STREET_4',
            'type' => 'varchar',
            'len' => 80,
        ),
        'shipping_address_street_number' => array(
            'name' => 'shipping_address_street_number',
            'vname' => 'LBL_SHIPPING_ADDRESS_STREET_NUMBER',
            'type' => 'varchar',
            'len' => 10,
        ),
        'shipping_address_street_number_suffix' => array(
            'name' => 'shipping_address_street_number_suffix',
            'vname' => 'LBL_SHIPPING_ADDRESS_STREET_NUMBER_SUFFIX',
            'type' => 'varchar',
            'len' => 25,
        ),
        'shipping_address_attn' => array(
            'name' => 'shipping_address_attn',
            'vname' => 'LBL_SHIPPING_ADDRESS_ATTN',
            'type' => 'varchar',
            'len' => '150',
            'comment' => 'additonal attention field for the address',
            'group' => 'shipping_address',
            'merge_filter' => 'enabled',
        ),
        'shipping_address_city' => array(
            'name' => 'shipping_address_city',
            'vname' => 'LBL_SHIPPING_ADDRESS_CITY',
            'type' => 'varchar',
            'len' => 100,
            'group' => 'shipping_address',
            'comment' => 'The city used for the shipping address',
            'merge_filter' => 'enabled',
        ),
        'shipping_address_district' => array(
            'name' => 'shipping_address_district',
            'vname' => 'LBL_SHIPPING_ADDRESS_DISTRICT',
            'type' => 'varchar',
            'len' => 100,
            'group' => 'shipping_address',
            'comment' => 'The district used for the shipping address',
        ),
        'shipping_address_state' => array(
            'name' => 'shipping_address_state',
            'vname' => 'LBL_SHIPPING_ADDRESS_STATE',
            'type' => 'varchar',
            'len' => 100,
            'group' => 'shipping_address',
            'comment' => 'The state used for the shipping address',
            'merge_filter' => 'enabled',
        ),
        'shipping_address_postalcode' => array(
            'name' => 'shipping_address_postalcode',
            'vname' => 'LBL_SHIPPING_ADDRESS_POSTALCODE',
            'type' => 'varchar',
            'len' => 20,
            'group' => 'shipping_address',
            'comment' => 'The zip code used for the shipping address',
            'merge_filter' => 'enabled',
        ),
        'shipping_address_pobox' => array(
            'name' => 'shipping_address_pobox',
            'vname' => 'LBL_SHIPPING_ADDRESS_POBOX',
            'type' => 'varchar',
            'len' => 20,
            'group' => 'shipping_address',
            'comment' => 'PO Box for the address',
            'merge_filter' => 'enabled',
        ),
        'shipping_address_country' => array(
            'name' => 'shipping_address_country',
            'vname' => 'LBL_SHIPPING_ADDRESS_COUNTRY',
            'type' => 'varchar',
            'group' => 'shipping_address',
            'comment' => 'The country used for the shipping address',
            'merge_filter' => 'enabled',
        ),
        'shipping_address_latitude' => array(
            'name' => 'shipping_address_latitude',
            'vname' => 'LBL_SHIPPING_ADDRESS_LATITUDE',
            'type' => 'double',
            'group' => 'shipping_address',
        ),
        'shipping_address_longitude' => array(
            'name' => 'shipping_address_longitude',
            'vname' => 'LBL_SHIPPING_ADDRESS_LONGITUDE',
            'type' => 'double',
            'group' => 'shipping_address',
        ),
        'originating_id' => array(
            'name' => 'originating_id',
            'source' => 'non-db'
        ),
        'parent_documents' => [
            'name' => 'parent_documents',
            'vname' => 'LBL_PARENT_DOCUMENTS',
            'type' => 'link',
            'source' => 'non-db',
            'module' => 'SalesDocs',
            'relationship' => 'salesdocsflow',
            'side' => 'right'
        ],
        'child_documents' => [
            'name' => 'child_documents',
            'vname' => 'LBL_CHILD_DOCUMENT',
            'type' => 'link',
            'source' => 'non-db',
            'module' => 'SalesDocs',
            'relationship' => 'salesdocsflow',
            'side' => 'left'
        ]
    ),
    'indices' => array(
        array('name' => 'idx_salesdocs_id_del', 'type' => 'index', 'fields' => array('id', 'deleted'),),
        array('name' => 'idx_salesdocs_sdtype_del', 'type' => 'index', 'fields' => array('salesdoctype', 'deleted'),),
        array('name' => 'idx_salesdocs_sdparty_del', 'type' => 'index', 'fields' => array('salesdocparty', 'deleted'),),
        array('name' => 'idx_salesdocs_sdnumber', 'type' => 'index', 'fields' => array('salesdocnumber')),
        array('name' => 'idx_salesdocs_inco1_del', 'type' => 'index', 'fields' => array('incoterm1', 'deleted'),),
        array('name' => 'idx_salesdocs_accopid', 'type' => 'index', 'fields' => array('account_op_id')),
        array('name' => 'idx_salesdocs_accrpid', 'type' => 'index', 'fields' => array('account_rp_id')),
        array('name' => 'idx_salesdocs_accppid', 'type' => 'index', 'fields' => array('account_pp_id')),
        array('name' => 'idx_salesdocs_accirid', 'type' => 'index', 'fields' => array('account_ir_id')),
        array('name' => 'idx_salesdocs_parentdel', 'type' => 'index', 'fields' => array('parent_id', 'parent_type', 'deleted')),
        array('name' => 'idx_salesdocs_valid_from_date', 'type' => 'index', 'fields' => array('valid_from_date')),
        array('name' => 'idx_salesdocs_valid_until_date', 'type' => 'index', 'fields' => array('valid_until_date')),
        array('name' => 'idx_salesdocs_consumeropid', 'type' => 'index', 'fields' => array('consumer_op_id')),
        array('name' => 'idx_salesdocs_consumerrpid', 'type' => 'index', 'fields' => array('consumer_rp_id'))
    ),
    'relationships' => array(
        'salesdocs_companycodes' => array(
            'rhs_module' => 'SalesDocs',
            'rhs_table' => 'salesdocs',
            'rhs_key' => 'companycode_id',
            'lhs_module' => 'CompanyCodes',
            'lhs_table' => 'companycodes',
            'lhs_key' => 'id',
            'relationship_type' => 'one-to-many'
        ),
        'salesdocs_contacts' => array(
            'rhs_module' => 'SalesDocs',
            'rhs_table' => 'salesdocs',
            'rhs_key' => 'contact_id',
            'lhs_module' => 'Contacts',
            'lhs_table' => 'contacts',
            'lhs_key' => 'id',
            'relationship_type' => 'one-to-many'
        ),
        'salesdocs_accountsop' => array(
            'rhs_module' => 'SalesDocs',
            'rhs_table' => 'salesdocs',
            'rhs_key' => 'account_op_id',
            'lhs_module' => 'Accounts',
            'lhs_table' => 'accounts',
            'lhs_key' => 'id',
            'relationship_type' => 'one-to-many'
        ),
        'salesdocs_accountspp' => array(
            'rhs_module' => 'SalesDocs',
            'rhs_table' => 'salesdocs',
            'rhs_key' => 'account_pp_id',
            'lhs_module' => 'Accounts',
            'lhs_table' => 'accounts',
            'lhs_key' => 'id',
            'relationship_type' => 'one-to-many'
        ),
        'salesdocs_accountsir' => array(
            'rhs_module' => 'SalesDocs',
            'rhs_table' => 'salesdocs',
            'rhs_key' => 'account_ir_id',
            'lhs_module' => 'Accounts',
            'lhs_table' => 'accounts',
            'lhs_key' => 'id',
            'relationship_type' => 'one-to-many'
        ),
        'salesdocs_contactsop' => array(
            'rhs_module' => 'SalesDocs',
            'rhs_table' => 'salesdocs',
            'rhs_key' => 'contact_op_id',
            'lhs_module' => 'Contacts',
            'lhs_table' => 'contacts',
            'lhs_key' => 'id',
            'relationship_type' => 'one-to-many'
        ),
        'salesdocs_consumerop' => array(
            'rhs_module' => 'SalesDocs',
            'rhs_table' => 'salesdocs',
            'rhs_key' => 'consumer_op_id',
            'lhs_module' => 'Consumers',
            'lhs_table' => 'consumers',
            'lhs_key' => 'id',
            'relationship_type' => 'one-to-many'
        ),
        'salesdocs_consumerrp' => array(
            'rhs_module' => 'SalesDocs',
            'rhs_table' => 'salesdocs',
            'rhs_key' => 'consumer_rp_id',
            'lhs_module' => 'Consumers',
            'lhs_table' => 'consumers',
            'lhs_key' => 'id',
            'relationship_type' => 'one-to-many'
        ),
        'salesdocs_accountsrp' => array(
            'rhs_module' => 'SalesDocs',
            'rhs_table' => 'salesdocs',
            'rhs_key' => 'account_rp_id',
            'lhs_module' => 'Accounts',
            'lhs_table' => 'accounts',
            'lhs_key' => 'id',
            'relationship_type' => 'one-to-many'
        ),
        'salesdocs_contactsrp' => array(
            'rhs_module' => 'SalesDocs',
            'rhs_table' => 'salesdocs',
            'rhs_key' => 'contact_rp_id',
            'lhs_module' => 'Contacts',
            'lhs_table' => 'contacts',
            'lhs_key' => 'id',
            'relationship_type' => 'one-to-many'
        ),
        'salesdocs_salesvouchers' => array(
            'lhs_module' => 'SalesDocs',
            'lhs_table' => 'salesdocs',
            'lhs_key' => 'id',
            'rhs_module' => 'SalesVouchers',
            'rhs_table' => 'salesvouchers',
            'rhs_key' => 'salesdoc_id',
            'relationship_type' => 'one-to-many'
        ),
        'salesdocsl_approved_user' => array(
            'lhs_module' => 'Users',
            'lhs_table' => 'users',
            'lhs_key' => 'id',
            'rhs_module' => 'SalesDocs',
            'rhs_table' => 'salesdocs',
            'rhs_key' => 'approved_user_id',
            'relationship_type' => 'one-to-many'
        ),
        'outputtemplate_salesdocs' => [
            'lhs_module' => 'OutputTemplates',
            'lhs_table' => 'outputtemplates',
            'lhs_key' => 'id',
            'rhs_module' => 'SalesDocs',
            'rhs_table' => 'salesdocs',
            'rhs_key' => 'outputtemplate_id',
            'relationship_type' => 'one-to-many',
        ],
        'salesdocs_approved_user' => [
            'lhs_module' => 'Users',
            'lhs_table' => 'users',
            'lhs_key' => 'id',
            'rhs_module' => 'SalesDocs',
            'rhs_table' => 'salesdocs',
            'rhs_key' => 'approved_user_id',
            'relationship_type' => 'one-to-many',
        ],
        'salesdocs_serviceorders_parent' => array(
            'lhs_module' => 'ServiceOrders',
            'lhs_table' => 'serviceorders',
            'lhs_key' => 'id',
            'rhs_module' => 'SalesDocs',
            'rhs_table' => 'salesdocs',
            'rhs_key' => 'parent_id',
            'relationship_type' => 'one-to-many',
            'relationship_role_column' => 'parent_type',
            'relationship_role_column_value' => 'ServiceOrders',
        ),
        'salesdocs_projects_parent' => array(
            'lhs_module' => 'Projects',
            'lhs_table' => 'projects',
            'lhs_key' => 'id',
            'rhs_module' => 'SalesDocs',
            'rhs_table' => 'salesdocs',
            'rhs_key' => 'parent_id',
            'relationship_type' => 'one-to-many',
            'relationship_role_column' => 'parent_type',
            'relationship_role_column_value' => 'Projects',
        ),
        'salesdocs_opportunities_parent' => array(
            'lhs_module' => 'Opportunities',
            'lhs_table' => 'opportunities',
            'lhs_key' => 'id',
            'rhs_module' => 'SalesDocs',
            'rhs_table' => 'salesdocs',
            'rhs_key' => 'parent_id',
            'relationship_type' => 'one-to-many',
            'relationship_role_column' => 'parent_type',
            'relationship_role_column_value' => 'Opportunities',
        ),

    ),
    'optimistic_lock' => true
);




VardefManager::createVardef('SalesDocs', 'SalesDoc', array('default', 'assignable'));
//BEGIN PHP7.1 compatibility: avoid PHP Fatal error:  Uncaught Error: Cannot use string offset as an array
global $dictionary;
//END
unset($dictionary['SalesDoc']['fields']['name']);
