<?php
namespace SpiceCRM\modules\ContactsOnlineProfiles;

use SpiceCRM\data\BeanFactory;
use SpiceCRM\data\SugarBean;
/***** SPICE-SUGAR-HEADER-SPACEHOLDER *****/

/*********************************************************************************
 * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc.
 * All Rights Reserved.
 * Contributor(s): ______________________________________..
 ********************************************************************************/
// Contact is used to store customer information.
class ContactsOnlineProfile extends SugarBean
{

    var $table_name = "contactsonlineprofiles";
    var $object_name = "ContactsOnlineProfile";
    var $module_dir = 'ContactsOnlineProfiles';

    function __construct()
    {
        parent::__construct();
    }

    function bean_implements($interface)
    {
        switch($interface){
            case 'ACL':return true;
        }
        return false;
    }

    function get_summary_text()
    {
        return $this->name;
    }

    function save($check_notify = false, $fts_index_bean = true)
    {
        if (empty($this->parent_id)) {
            switch ($this->parent_type) {
                default:
                    if (!empty($this->email)) {
                        $contact = BeanFactory::getBean('Contacts');
                        if ($contact->retrieve_by_email_address($this->email) === false) {
                            $contact->salutation = $this->salutation;
                            $contact->first_name = $this->first_name;
                            $contact->last_name = $this->last_name;
                            $contact->email1 = $this->email;
                            $contact->primary_address_street = $this->profile_address_street;
                            $contact->primary_address_city = $this->profile_address_city;
                            $contact->primary_address_postalcode = $this->profile_address_postalcode;
                            $contact->primary_address_country = $this->profile_address_country;
                            $contact->gdpr_data_agreement = $this->gdpr_data_agreement;
                            $contact->save();
                        }

                        $this->parent_type = 'Contacts';
                        $this->parent_id = $contact->id;
                    }
                    break;
            }
        }

        if (empty($this->name)) $this->name = $this->profile_source_name;

        return parent::save($check_notify, $fts_index_bean); // TODO: Change the autogenerated stub
    }

}
