<?php
/***** SPICE-HEADER-SPACEHOLDER *****/
namespace SpiceCRM\modules\ServiceTicketNotes;

use SpiceCRM\data\SugarBean;

class ServiceTicketNote extends SugarBean {
    public $module_dir = 'ServiceTicketNotes';
    public $object_name = 'ServiceTicketNote';
    public $table_name = 'serviceticketnotes';


    public function get_summary_text(){
        return $this->name;
    }

    public function bean_implements($interface){
        switch($interface){
            case 'ACL':return true;
        }
        return false;
    }

    public function save($check_notify = false, $fts_index_bean = true)
    {
        $this->name = strlen($this->description) > 50 ?  substr(html_entity_decode(strip_tags($this->description)), 0, 47) . '...':   substr(html_entity_decode(strip_tags($this->description)), 0, 50);
        return parent::save($check_notify, $fts_index_bean); // TODO: Change the autogenerated stub
    }

}
